name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install root dependencies
        run: npm install --workspaces=false || true
      - name: Install backend dependencies
        run: cd server && npm install
      - name: Lint backend
        run: cd server && npm run lint || true
      - name: Build backend
        run: cd server && npm run build
      - name: Install frontend dependencies
        run: cd web && npm install
      - name: Lint frontend
        run: cd web && npm run lint || true
      - name: Build frontend
        run: cd web && npm run build

  deploy-vercel:
    needs: build-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./web
          prod: true 